### ISSUE TITLE
Crash Course 1: GitHub and Markdown

### ISSUE THREAD

**Issue by LuckierDodge** [NIURoverTeam/crash-course#1]
1. Create a new branch named `<first name>-<last name>`
1. In your new branch, create a file in the `Introductions` directory named `<Your Name>.md`
    1. The file should be a short introduction of yourself, and should include 3 things: at least 2 headers, a numbered or bullet pointed list, and a link. The actual content is up to you.
    1. An example has already been provided in the `Introductions` directory for you to reference
    1. [Markdown Syntax Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
1. Once you've committed your new file to your branch, submit a pull request to merge your branch to master.
1. Finally, make a comment on this issue, letting us know that you're ready to merge.

Don't forget to use your resources, especially the [Wiki](https://github.com/NIURoverTeam/RoverCoreOS/wiki), and don't be afraid to shoot me a message on Slack!

**Comment by DrakeProvost** [comment]
I am ready to merge.

**Comment by filopj** [comment]
Ready to Merge

**Comment by VenkataAnirudh-T** [comment]
Ready to merge.
